### ISSUE TITLE
Context elements not getting populated , if multiple contexts are there.

### ISSUE THREAD

**Issue by ATHULKNAIR** [medblocks/medblocks-ui#43]
Medblocks UI components :

<mb-input-multiple
	repeatsuffix="problem_diagnosis_name"
	repeatprefix="aarthy.clinicalnotes.v1/diagnosis_of_right_eye"
	path="aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/problem_diagnosis_name"
/>
<mb-context path="aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/language" />
<mb-context path="aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/encoding" />

Composition samples :
 
{
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/problem_diagnosis_name":"xxxxx",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/language|code":"en",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/language|terminology":"ISO_639-1"
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/encoding|code":"IN",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/encoding|terminology":"ISO_3166-1"
}

when there is only single input, the context elements are getting populated. But when there are multiple inputs, 

{
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/problem_diagnosis_name":"xxxxx",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:1/problem_diagnosis_name":"yyyyy",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/language|code":"en",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/language|terminology":"ISO_639-1"
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/encoding|code":"IN",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/encoding|terminology":"ISO_3166-1"
}

missing context elements :
 
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:1/language|code":"en",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:1/language|terminology":"ISO_639-1"
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:1/encoding|code":"IN",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:1/encoding|terminology":"ISO_3166-1"

**Comment by sidharthramesh** [comment]
Hey @ATHULKNAIR 
This seems to be an issue when using the multiple elements with a prefix and suffix - since all of those values get populated under path:0/diagnosis_name.

Can you also post the internal .data property of the mb-form element before and after submitting for reference?

**Comment by ATHULKNAIR** [comment]
The composition made from this : 

{
    "aarthy.clinicalnotes.v1/category|code": "433",
    "aarthy.clinicalnotes.v1/category|value": "event",
    "aarthy.clinicalnotes.v1/category|terminology": "openehr",
    "aarthy.clinicalnotes.v1/context/start_time": "2022-07-19T09:18:28.118Z",
    "aarthy.clinicalnotes.v1/context/setting|code": "238",
    "aarthy.clinicalnotes.v1/context/setting|value": "other care",
    "aarthy.clinicalnotes.v1/context/setting|terminology": "openehr",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/problem_diagnosis_name": "asdads",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:1/problem_diagnosis_name": "asdasd",
    "aarthy.clinicalnotes.v1/diagnosis_of_left_eye:0/problem_diagnosis_name": "asdasd",
    "aarthy.clinicalnotes.v1/diagnosis_of_left_eye:1/problem_diagnosis_name": "asdasdasd",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/language|code": "en",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/language|terminology": "ISO_639-1",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/encoding|code": "UTF-8",
    "aarthy.clinicalnotes.v1/diagnosis_of_right_eye:0/encoding|terminology": "IANA_character-sets",
    "aarthy.clinicalnotes.v1/diagnosis_of_left_eye:0/language|code": "en",
    "aarthy.clinicalnotes.v1/diagnosis_of_left_eye:0/language|terminology": "ISO_639-1",
    "aarthy.clinicalnotes.v1/diagnosis_of_left_eye:0/encoding|code": "UTF-8",
    "aarthy.clinicalnotes.v1/diagnosis_of_left_eye:0/encoding|terminology": "IANA_character-sets",
    "aarthy.clinicalnotes.v1/composer|name": "Sidharth",
    "aarthy.clinicalnotes.v1/language|code": "en",
    "aarthy.clinicalnotes.v1/language|terminology": "ISO_639-1",
    "aarthy.clinicalnotes.v1/territory|code": "IN",
    "aarthy.clinicalnotes.v1/territory|terminology": "ISO_3166-1"
}

**Comment by sidharthramesh** [comment]
@ATHULKNAIR I'm assuming this issue is now resolved? Should we close?
