### ISSUE TITLE
mb-context not submitted from mb-form

### ISSUE THREAD

**Issue by Mo-la-machette** [medblocks/medblocks-ui#45]
Hello,

I followed @sidharthramesh tutorial from youtube. I have a problem from setting an mb-context 
Here is my mb-form : 

`<mb-fhir-form class="flex flex-col gap-3" on:mb-submit={handleSubmit}>
    <mb-context path="resourceType" data="Patient"></mb-context>
    <mb-input path="name[0].given[0]" label="Name"></mb-input>
    <mb-date path="birthDate" label="Date of Birth"></mb-date>
    <mb-buttons type=code path="gender" label="Gender">
      <mb-option value="male" label="Male"/>
      <mb-option value="female" label="Female"/>
      <mb-option value="other" label="Other"/>
    </mb-buttons>
    <mb-submit>
      <sl-button {loading} type="info">Submit</sl-button>
    </mb-submit>
  </mb-fhir-form>`

The context is set when i look up on the mb-element list before submitting. 
But in the handleSubmit method, the context of the resourceType doesn't appeared
Have you the same behaviour ?

Thanks for this tutorial, it's very great
Have a nice day 
Thomas

**Comment by sidharthramesh** [comment]
Hey @Mo-la-machette , seems like you figured it out?

**Comment by Mo-la-machette** [comment]
Hello @sidharthramesh 

Yes, since your video, the way to handle mb-context (use "bind" rather than "data" element) have changed and it's well documented on the main page of this repository.

My fault, sorry
Have nice day
Thomas
